### ISSUE TITLE
Tallow connects succesfully, but connections time out; 

### ISSUE THREAD

**Issue by usra30** [basil00/TorWall#10]
Not sure whats going on here; I'm trying to run tallow on top of openvpn. The firewall is programmed to allow tallow, tor, svchost and others should be going through fine; disabling firewall results in the same issues;disabling openvpn as well. tor browser works without a hitch.   I have winhttp proxy disabled; along with many of its dependencies. I see others had similar issues, any idea whats going on here? 

also is there away to divert tor browser traffic through tallow?

**Comment by basil00** [comment]
Tallow will block all non-Tor traffic by default, including traffic to the VPN server.

However, it might be possible to configure Tallow to also ignore the VPN traffic.  This can only be done by editing the `traffic.divert` file.  See the comments in the file for more information.
