### ISSUE TITLE
Can't install this thing

### ISSUE THREAD

**Issue by RUr1ck** [basil00/TorWall#12]
Hi,

I've tried to install it, but when I run 'make' I got this error

i686-w64-mingw32-gcc --std=c99 -O2 -I contrib//include/ -mwindows -mthreads -mno-ms-bitfields -m32 -Wall -DVERSION=   -c -o main.o main.c
make: i686-w64-mingw32-gcc: Command not found
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 127

**Comment by basil00** [comment]
As you probably figured out, you need to install the `mingw-w64` cross compiler.
