### ISSUE TITLE
Connection error, in company networks by proxy

### ISSUE THREAD

**Issue by carlosnewmusic** [basil00/TorWall#17]
does not connect to tor you should have an option to do it this way

**Comment by basil00** [comment]
If the company is forcing all traffic through a web proxy then tor traffic will be blocked.  This means Tallow will not work.

**Comment by carlosnewmusic** [comment]
yes but tor if it works with the correct configuration

**Comment by s1q** [comment]
Хуесосда, заебл. Пусть пойдет на хуй в своих ебусиз кроссовках. Ебаный
хуесос.
