### ISSUE TITLE
public address problem

### ISSUE THREAD

**Issue by i3130002** [basil00/TorWall#2]
I get a warning like this:

> You specified a public address '0.0.0.0:49097' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason....
> No, it's still there.  Exiting....

How to disable that port or force it to ignore ?

**Comment by i3130002** [comment]
I had another tor open after closing that it goes but the error still exists.

**Comment by basil00** [comment]
> Other people on the Internet might find your computer and use it as an open proxy.

This cannot happen - Tallow has its own internal firewall that automatically blocks all outside traffic to that port.
