### ISSUE TITLE
Rebuild and Update The Windows Version

### ISSUE THREAD

**Issue by SEODEMON** [basil00/TorWall#21]
I love this program but for some reason it stopped working awhile ago. .  Can you please rebuild and update the Windows version?

**Comment by basil00** [comment]
I tried the latest version (1.2) and it is working for me.  You could also try version 1.1.

Otherwise, it might be some other issue, like your network blocking Tor.

**Comment by SEODEMON** [comment]
Yes, my brother-in-law has a hardware firewall where he does try to block TOR.  However,  the Torifier software is working just fine.  Tallow no longer works.  Thank you.

**Comment by basil00** [comment]
Anything that blocks Tor will block Tallow.  I'm not sure how torifier works.

It may be possible to configure Tallow to use Tor bridges.  This requires editing Tallow's `torrc` file, but I'm not exactly sure how to do it and do not provide support.
