### ISSUE TITLE
redirect_tcp condition

### ISSUE THREAD

**Issue by renecn** [basil00/TorWall#24]
hi basil00, 
  I'm confused that in redirect_tcp function , why  (addr->Outbound && addr->Loopback ) represent  Tor ---> PC  path,  and (addr->Outbound && !addr->Loopback) represent PC ---> Tor ?
I think that  tor-->pc and pc--->tor are both addr->Loopback.   Also  pc--->tor is Outbound  and  tor-->pc  is Inbound,  

Can you give me an answer?

**Comment by basil00** [comment]
It means `addr->Outbound && !addr->Loopback` is a packet that is to be redirected to Tor, not already directed to Tor.
