### ISSUE TITLE
Using TorWall with SOCKS5 proxy client

### ISSUE THREAD

**Issue by fahminlb33** [basil00/TorWall#26]
I want to use TorWall as transparent proxy through a proxy client, but in this case replacing `tor` with `ss-local` and SOCKS5 (Shadowsocks protocol).

But I haven't succeed to redirect the traffic to `ss-local` using my modified TorWall. I simply changed CreateProcess from `tor.exe` to `ss-local.exe`

From Wireshark capture log, WinDivert also redirected outbound connection from `ss-local` to proxy server to local port, so infinite loop and timeout error on the browser.

I understand TorWall checks for Process ID from Tor to whitelist the connection, but when running `ss-local` the whitelist never gets called.

**Comment by basil00** [comment]
Tallow does not use SOCK5 but SOCK4a.  My guess is that this the main problem.

If `ss-local` spawns child processes then the process ID whitelisting may also not work.
