### ISSUE TITLE
unable to run using cmd

### ISSUE THREAD

**Issue by connected201** [basil00/TorWall#27]
hi, i try to run tallow.exe using cmd, but, i receive error that tallow cannot find hosts.deny and traffic.deny, but, if i just run tallow.exe in gui mode, all ok!

**Comment by basil00** [comment]
Are you running it from the `Tallow` home directory?  That's all I can think of off-hand.

**Comment by connected201** [comment]
Hi, yes, i need from console be in Tallow folder, when, i want to run it.
