### ISSUE TITLE
where can i get tor ( not tor browser ) for windows

### ISSUE THREAD

**Issue by geeksesi** [basil00/TorWall#29]
Hi,
i use tor as a sock proxy in linux and i need it also in windows.
i found it on your tallow ( and it can run ) but i think it's a old version. and i don't know how support obfs4 bridge.
do you know how can i get tor for windows ( or source code to compile my self ? )
please help me . thank you :)

**Comment by basil00** [comment]
You need to find the *Tor expert bundle* for Windows.  It should be available somewhere on the torproject website.
