### ISSUE TITLE
Question about Tallow's options

### ISSUE THREAD

**Issue by Engelberg** [basil00/TorWall#3]
Can you please explain the two checkboxes from the program?

* Force web-only
* Force SOCKS4a

Force them to do what?

What would be the combination of settings to use to route everything possible through Tor?  Is there an easy way to test that specific tcp messages sent and received by a program are going through Tallow/Tor as expected?

**Comment by basil00** [comment]
With *Force web-only* enabled Tallow will only divert web traffic (HTTP/HTTPS) via Tor.  All other non-web traffic will be blocked (i.e. prevented from leaving the computer and not sent via Tor).  With *Force web-only* disabled then all traffic (web and non-web) will be diverted via Tor.

With *Force SOCKS4a* enabled all connections must be initiated via a hostname (e.g. `google.com`) and direct connections to IP addresses are disallowed.  With *Force SOCKS4a* disabled, direct connections to IP addresses via Tor are allowed.  This is mainly useful for P2P applications.

**Comment by Engelberg** [comment]
A couple follow-up questions: 

1. Does Tallow handle localhost addresses intelligently (i.e., not sending them through Tor)?
2. Is there any tool I can use to confirm what traffic is and is not flowing through Tor when using Tallow with a specific application?

Thanks.

**Comment by basil00** [comment]
> Does Tallow handle localhost addresses intelligently (i.e., not sending them through Tor)?

Localhost is not sent via Tor.  Even if it were, the Tor network will reject such traffic.

> Is there any tool I can use to confirm what traffic is and is not flowing through Tor when using Tallow with a specific application?

You can try running Tallow from a `cmd` prompt, and it will print information about what is being diverted.  To independently verify you'd need some other tool such as Wireshark.
