### ISSUE TITLE
[BUG] Failed ot Open WinDivert Filter

### ISSUE THREAD

**Issue by Merith-TK** [basil00/TorWall#31]
![image](https://user-images.githubusercontent.com/10422110/68805956-af1bb880-0619-11ea-83cb-bfec94f1d9fe.png)

**Comment by basil00** [comment]
Is that Windows 7?  This error can occur if you attempt to run Tallow on an older version of Windows 7 that does not support SHA256 signatures.  To fix you need to update, or upgrade to Windows 10.

**Comment by Merith-TK** [comment]
Windows 7 on latest update i can get

**Comment by basil00** [comment]
The only thing I can suggest is to download the "C" variant of WinDivert 2.2.0 from here https://github.com/basil00/Divert/releases/tag/v2.2.0.

Extract the driver files (`WinDivert32.sys`/`WinDivert64.sys`) and replace the default Tallow versions.  If this does not work then nothing will.
