### ISSUE TITLE
Update to latest tor-win32-0.4.2.7

### ISSUE THREAD

**Issue by JohnPlanetary** [basil00/TorWall#35]
It may be a nice idea to keep tor files updated to the latest version available, currently: tor-win32-0.4.2.7, available from the web site: https://www.torproject.org/download/tor/ "Windows Expert Bundle".

**Comment by basil00** [comment]
One of the problems with this project is keeping up with the latest Tor.  I'd prefer to only do it for security fixes only, although I do not keep an eye on these things.

**Comment by basil00** [comment]
Btw, you can manually upgrade by replacing the Tor binary files in the Tallow home directory.  This should work provided the Tor interface/API has not changed in newer versions.

**Comment by sergeevabc** [comment]
Err… By the way, after installing Tallow 2.0, I get “Failed to open WinDivert filter: The system cannot find the path specified” after launching a shortcut on the Windows 7 desktop. Alas.

**Comment by basil00** [comment]
Windows 7 is past its end-of-life so is not supported anymore.  However, these kinds of issues can sometimes be solved by replacing the driver files with a different version, downloaded from here: https://github.com/basil00/Divert/releases/tag/v2.2.0

**Comment by gvanem** [comment]
> Windows 7 is past its end-of-life so is not supported anymore.

That's not the problem.  `The WinDivert.dll` can copy the .sys-file(s) to the wrong place. I've seen that running a 32-bit program, that a `WinDivert64.sys` gets copied to the current directory! And perhaps the `CurrentControlSet` node gets updated
with a wrong file-name. It's rather messy IMHO.
