### ISSUE TITLE
Allow custom UDP ports/ranges to bypass Tor?

### ISSUE THREAD

**Issue by slrslr** [basil00/TorWall#38]
Hello,
if i am using app that is using UDP, like a torrent client for example? maybe can be good if user can see the list of UDP connection attempts and allow certain UDP ports to connect directly (not via Tor) - at same time user is presented with the list of allowed ports and is warned these connections will not be anonymized. If bad idea or out of scope feature, please close. Thank you

**Comment by basil00** [comment]
Tor does not support UDP, so the current policy is just to block it.  You can try editing the `traffic.deny` file, but I think Tallow will still block it internally.

I think it is possible to run a torrent client with Tallow, but it would be restricted to the TCP protocol, and you would need to select the option to allow direct IP connections.  Torrenting over Tor is also not encouraged.

**Comment by slrslr** [comment]
> Tor does not support UDP ... Torrenting over Tor is also not encouraged.

yes, i was rather thinking that the excluded ports would cause TorWall not to force this traffic thru the Tor, but dirrectly clearnet (or, as the case may be via VPN, which is set in the system as the main interface)

**Comment by basil00** [comment]
You can somewhat control the traffic using the `traffic.divert` and `traffic.deny` files, so perhaps look into that.
