### ISSUE TITLE
Why addr->Outbound value always set to 1 in the send_packet() function ?

### ISSUE THREAD

**Issue by dustreading** [basil00/TorWall#39]
I know that some traffic such tcp traffic from 127.0.0.1 is Loopback, which should be set to 1. but the DNS query traffic is not and it is still set to 1, so how does the DNS traffic go back? I'm a little confused.

**Comment by basil00** [comment]
I am not why sure it is like that.  However, it is harmless since injecting an inbound packet in the outbound path will still work.
