### ISSUE TITLE
tor proxy server on a other dedicated machine

### ISSUE THREAD

**Issue by h3y** [basil00/TorWall#4]
Hello how  i  can use tallow when i have a tor proxy server on a other dedicated machine? Is it possible to realize it?

**Comment by h3y** [comment]
how I can use my socks5 proxy server instead of a network tor?

**Comment by basil00** [comment]
It is currently not possible to do this since the traffic to the dedicated proxy will be blocked by Tallow.

**Comment by h3y** [comment]
And if i install a local proxy server and it will transmit traffic to an external proxy, is it possible?  Will be blocked through rules?

**Comment by basil00** [comment]
Basically any outbound traffic except from Tor itself will be blocked.  I may look at making this configurable in future versions.  However, this is not so simple because Tallow must completely hijack DNS regardless.
