### ISSUE TITLE
Allow RDP connections without Tor

### ISSUE THREAD

**Issue by loadcorp** [basil00/TorWall#41]
Hi,

First of all, thank you for this program!

My question is about: how can I allow RDP connection (I mean without Torification) in Tallow?

The main reason for this, I want to connect to my server via RDP without Tor, but when I want to start serfing via browser for example, I want keep using Tor connection without any affect for RDP. Is it possible?

**Comment by basil00** [comment]
It should be possible provided (1) RDP used TCP, and (2) by editing the `traffic.divert` file to exclude RDP traffic (e.g., by port number).  There should be instructions inside the `traffic.divert` file on how to do it.
